### ISSUE TITLE
MediaPipe hands includes the z coordinate in other languages such as python

### ISSUE THREAD

**Issue by delebash** [MIDIBlocks/handsfree#100]
Unfortunately the javascript api is for some reason different.  Several issues have been created requesting a fix for this.  You probably already know.  Nice work.  I am working on using this technology for motion capture take a look at a very very alpha test.  https://www.youtube.com/watch?v=j6JboJIlpfM  The main problem is how to get rid of the jitter otherwise it is not really usable.  I am using the python version at the moment so I can get the 3D coordinates.  Any thoughts on how to get rid of the jitter?

Thanks, nice work look forward to your progress!

**Comment by MIDIBlocks** [comment]
Oh very nice work! Yeah I've started an issue about the z coordinates. Unfortunately the APIs aren't standardized between platforms (or even between models) but the issue has been raised in [their forums](https://groups.google.com/g/mediapipe/c/fixP-LmmsME), in the [GitHub repo](https://github.com/google/mediapipe/issues/1392), and through DMs. I have email receipts on those, so I'll let you know as soon as I know!

As for the jitter I use a technique called [Tweening](https://handsfree.js.org/ref/method/TweenMax.html). It doesn't get rid of it completely, but it smoothens it out over x time so it's less noticeable with the drawback that there's a very small, often imperceptible latency (since it needs to average out over multiple frames).

Your use case is a complex because you would need to tween all 21 landmarks for both hands. I'm not sure how you would do this with Python, but some pseudocode with JavaScript would be:

```js
// Create the object to store our tween values
// - These are the actual values we will end up using to update our app
let curTween = [
  // Left hand landmarks
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // x
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // y
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // z
  ],
  // Right hand landmarks
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // x
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // y
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // z
  ],
]

// Inside your loop
onWebcamFrame = (hands) => {
  if (!hands.multiHandLandmarks) return

  // loop through each hand
  hands.multiHandLandmarks.forEach((hand, n) => {
    // Store our landmarks in a format like curTween
    const newTween = []
    hand.forEach((landmark, n) => {
      newTween[n] = landmark.x
      newTween[n + 21] = landmark.y
      newTween[n + 42] = landmark.z
    })

    // Tween landmarks over 1 second
    TweenMax.to(curTween[n], 1, {
      ...newTween,
      
      // Some settings to make smoothing better
      overwrite: true,
      ease: 'linear.easeNone',
      immediate: true
    })
  })

  // Your values are now ready to use
  curTween.forEach((hand, side) => {
    for (let landmark = 0; landmark < 21; landmark++) {
      // A method that updates your 3D model (hand, x, y, z)
      update3DFinger(side, hand[landmark], hand[landmark + 21], hand[landmark + 42])
    }
  })
}
```

There may be Tweening libraries in Python that don't require all those crazy loops, but hopefully this can get you started. I'll work on baking all this into Handsfree.js for the 2D Hands model and will update you when 3D is ready!

**Comment by delebash** [comment]
Thanks for the example code. This is an awesome project!
