### ISSUE TITLE
Weboji Example: All Oz Ramos tweets unavailable

### ISSUE THREAD

**Issue by shakhbulatgaz** [MIDIBlocks/handsfree#136]
All Tweets in the "examples" section of  are unavailable, since the account no longer exists.

That section needs to be refreshed.

https://handsfree.js.org/ref/model/weboji.html#examples

**Comment by labofoz** [comment]
Hi, I'm currently homeless (technically just displaced now) and deleted my social medias mostly out of shame for the fact that I wasn't able to generate enough money/support with Handsfree.js. For now I'm not publicly working on the library, but I have tons of new examples and a methods that I've been working on to keep busy.

Once I have housing I will go full blast into this project again, but it's already been 2 months :(

I'm working on moving the documentation to Notion which will be much easier for me to maintain, and have started moving the examples here: https://www.notion.so/901ff075d8df4bd7b9500d134c22038b?v=f33d13f1c67b458487250992a8501e2c

Another link that might help is the WordPress documentation at https://handsfree.dev which explores my other tools like the Bookmarklet, Face Coding, and more.

**Comment by labofoz** [comment]
Whoops sorry this is the correct Notion link: https://labofoz.notion.site/901ff075d8df4bd7b9500d134c22038b?v=f33d13f1c67b458487250992a8501e2c

It currently has 25+ example videos and some of them also include the source code. I have at least another 25 examples for Weboji, since face tracking was the genesis of Handsfree.js but it'll take time to migrate everything
