### ISSUE TITLE
Using handsfree on a video

### ISSUE THREAD

**Issue by Obinnabii** [MIDIBlocks/handsfree#67]
Is there a way to run handsfree on a recorded video in order to log face-tilts, rotation, and angles, or do I need to use Weboji directly. The videos are of people doing tasks with handsfree.js which is why I would like to use the actual API for tilt logging.

**Comment by MIDIBlocks** [comment]
Oh this is a great use case! It's possible by [using Weboji directly](https://github.com/jeeliz/jeelizWeboji/blob/master/doc/jeefacetransferAPI.pdf) and setting the `videoSettings.videoElement` when using `JEELIZTRANSFERAPI.init()`, something like:

```js
JEELIZTRANSFERAPI.init({
  videoSettings: {
    videoElement: document.querySelector('#my-video')
  }
})
```

However, this would be pretty easy to add to the API. I should have this added to the next release and documented sometime tomorrow.

Thanks for starting this issue!

**Comment by MIDIBlocks** [comment]
This should now be working with Handsfree.js `7.2.13`! Here's an example:

HTML:
```html
<video id="my-video" src="/my-video.mp4" controls></video>
```

JavaScript:
```js
handsfree = new Handsfree({
  face: {
    enabled: true,
    videoSettings: {
      videoElement: document.querySelector('#my-video')
    }
  }
})
```

Here, `#my-video` can be a `<video>`, a `<canvas>`, or even an image or GIF with `<img>`. The documentation for this will be here (still cleaning it up): https://handsfree.js.org/docs/face/#setup

Some gotchas which I'll fix in a future issue:
- You can't switch back and forth from webcam to video yet. If you need both to run at the same time then you'll need to create two handsfree instances with separate configs
- To flip the video, style it through css with: `#my-video {transform: scale(-1, 1)}`. If that doesn't work, try the canvas `canvas {transform: scale(-1, 1)}`

**Comment by Obinnabii** [comment]
Thank you so much!

**Comment by Obinnabii** [comment]
Is there a way to speed up the process? since the video is pre-recorded, can handsfree produce a recording/log without playing the entire video?

**Comment by MIDIBlocks** [comment]
That's a good question! I don't know to be honest as I believe you may be the first one to work with pre-recorded videos. I'm thinking the answer is no as it's already set to run as fast as possible. You may be able to fake the speed up process by skipping every 4th, 3rd, or even 2nd frame and just averaging things out but I wouldn't know how to do that unfortunately and it might not be a good solution in your case

I do plan on making Handsfree.js work within Node without a browser and you'll definitely be able to speed it up then but that won't happen for a few months at least

I apologize for not having great answers because this is a great use case. I should be done with the next release tonight or tomorrow and I would be able to help you solve this a lot better then!

**Comment by Obinnabii** [comment]
No need to apologize man, this is a great API!
I appreciate all the work you have done so far.
